// apps/vue-playground/src/components/UserProfile.vue
<script setup lang="ts">
import { useModalor } from '@modalor/vue'

const props = defineProps<{
  name: string
}>()

const { onOk, resolve, isOkLoading } = useModalor()

onOk(() => {
  isOkLoading.value = true

  setTimeout(() => {
    isOkLoading.value = false
    resolve(null)
  }, 2000)
})
</script>

<template>
  <div>
    User Profile:

    <br>

    my name is {{ props.name }}
  </div>
</template>

// apps/react-playground/src/components/UserProfile/index.tsx
import { Input } from "@chakra-ui/react"
import { useModalor } from "@modalor/react"
import { useEffect, useState } from "react"



export const UserProfile = ({ name: initialName }: { name: string }) => {

  const { onOk, resolve, setOkDisabled } = useModalor<{ name: string }>()

  const [name, setName] = useState(initialName)

  onOk(() => {
    resolve({ name })
  })

  useEffect(() => {
    setOkDisabled(name === initialName || !name)
  }, [name])


  return <div>

    <h1>User Profile</h1>
    <p>Old Name: {name}</p>
    <br />
    <br />
    Input new name:

    <Input value={name} onChange={(e) => setName(e.target.value)} />
  </div>
}
