// apps/react-playground/src/components/Confirm/index.tsx
import { Input } from '@chakra-ui/react'
import { useModalor } from '@modalor/react'
import { useEffect, useState } from 'react'

export function Confirm() {
  const { onOk, resolve, setOkDisabled, setOkLoading } = useModalor()

  const [value, setValue] = useState('')

  useEffect(() => {
    console.log('value', value)
    setOkDisabled(value !== 'confirm')
  }, [value, setOkDisabled])

  onOk(() => {
    setOkLoading(true)
    setTimeout(() => {
      resolve(value)
      setOkLoading(false)
    }, 1000)
  })

  return (
    <div>
      type "confirm" to confirm:

      <br />

      <Input value={value} onChange={e => setValue(e.target.value)} />
    </div>
  )
}

// apps/vue-playground/src/components/Confirm.vue
<script setup lang="ts">
import { useModalor } from '@modalor/vue'
import { ref, watch } from 'vue'

const text = ref('')

const { onOk, resolve, isOkLoading, isOkDisabled } = useModalor()

watch(text, (value) => {
  isOkDisabled.value = value !== 'confirm'

  console.log(isOkDisabled.value)
}, {
  immediate: true,
})

onOk(() => {
  isOkLoading.value = true
  setTimeout(() => {
    isOkLoading.value = false
    resolve(null)
  }, 2000)
})
</script>

<template>
  <div>
    type "confirm" to confirm:

    <br>

    <v-text-field v-model="text" label="text" />
  </div>
</template>
